### ISSUE TITLE
Update file and keep annotations

### ISSUE THREAD

**Issue by JimHokanson** [ScholarTools/mendeley_python#10]
The client library does not handle updating an entries' file well. Specifically, the file will not sync when updated, unless the file is first removed from Mendeley, and then readded. Additionally, deletion of the file means that the annotations are lost. 

The user may choose to update the file if the word recognition has not been run on the file, or if a page needs to be rotated.

We should allow specification of a file path and a file id that does the following:
1) Grabs all the annotations
2) Deletes the file associated with the entry on the Mendeley server
3) Adds the new file to the entry
4) Readds the annotations to the file. For OCR this is probably going to be fine, a page rotation might cause a problem, particularly since in the client you can't add annotations outside of the page limits. Misplaced annotations on that page wouldn't be the end of the world, just the client crashing from rendering would not be good.

**Comment by ksarmentrout** [comment]
Done. Page rotation seems to be supported.
