### ISSUE TITLE
Archival code structure

### ISSUE THREAD

**Issue by JimHokanson** [ScholarTools/mendeley_python#12]
The archival code is a bit strange in that it runs the code on importing. This is very unexpected behavior and should probably be changed.

Also, by default the code currently archives to the repository folder. The user should need to specify a save folder path, either by an input, the config, or by graphical selection, perhaps via:
http://stackoverflow.com/questions/3579568/choosing-a-file-in-python-with-simple-dialog

I'm also curious as to why the archive option isn't available through the library, e.g. library.archive()

Also, I had meant to only have one zip file instead of multiple files, I changed my mind on this halfway through the discussion and it probably was unclear. The file then should contain multiple folders as well as a single meta data file. Feel free to champion a different structure ...

**Comment by ksarmentrout** [comment]
The answer in the SO link you posted uses Tkinter, which I'd like to avoid. I'll be using PyQt's QFileDialog (https://doc.qt.io/qt-5/qfiledialog.html), which I'm mainly just posting here to remind myself. I'll implement it tomorrow. 

Your other points should all be fixed now.

**Comment by ksarmentrout** [comment]
Users are now able to select file paths, and retries on connection failures / interrupts are now supported.
